/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AccountResource (
  resourceId: Option[ResourceId],
  /* ISO20022: Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362 \"Banking - Banking telecommunication messages - Business identification code (BIC)\".  */
  bicFi: Option[String],
  accountId: Option[AccountIdentification],
  /* Label of the PSU account In case of a delayed debit card transaction set, the name shall specify the holder name and the imputation date  */
  name: String,
  /* Specifications that might be provided by the ASPSP - characteristics of the account - characteristics of the relevant card  */
  details: Option[String],
  /* Case of a set of pending card transactions, the APSP will provide the relevant cash account the card is set up on. */
  linkedAccount: Option[String],
  /* Specifies the usage of the account - PRIV: private personal account - ORGA: professional account  */
  usage: Option[AccountResourceEnums.Usage],
  /* Specifies the type of the account - CACC: Cash account - CARD: List of card based transactions  */
  cashAccountType: AccountResourceEnums.CashAccountType,
  /* Product Name of the Bank for this account, proprietary definition  */
  product: Option[String],
  /* Currency used for the account */
  currency: String,
  /* list of balances provided by the ASPSP */
  balances: Option[Seq[BalanceResource]],
  /* Relationship between the PSU and the account - Account Holder - Co-account Holder - Attorney */
  psuStatus: Option[String],
  links: AccountLinks
) extends ApiModel

object AccountResourceEnums {

  type Usage = Usage.Value
  type CashAccountType = CashAccountType.Value
  object Usage extends Enumeration {
    val PRIV = Value("PRIV")
    val ORGA = Value("ORGA")
  }

  object CashAccountType extends Enumeration {
    val CACC = Value("CACC")
    val CARD = Value("CARD")
  }

}

