/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class BalanceResource (
  /* Label of the balance */
  name: String,
  balanceAmount: AmountType,
  balanceType: BalanceStatus,
  /* Timestamp of the last change of the balance amount */
  lastChangeDateTime: Option[DateTime],
  /* Reference date for the balance */
  referenceDate: Option[Date],
  /* Identification of the last committed transaction. This is actually useful for instant balance.  */
  lastCommittedTransaction: Option[String]
) extends ApiModel


