/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Beneficiary (
  /* Id of the beneficiary */
  id: Option[String],
  /* The ASPSP having not implemented the trusted beneficiaries list must not set this flag. Otherwise, the ASPSP indicates whether or not the beneficiary has been registered by the PSU within the trusted beneficiaries list. - true: the beneficiary is actually a trusted beneficiary (when set by ASPSP) - false: the beneficiary is not a trusted beneficiary          The PISP may set this flag to \"true\" to indicate that the PSU considers the beneficiary as trusted and to be inserted within the trusted beneficiaries list, as far as this feature was implemented by the ASPSP.   - true: the beneficiary should be registered as a trusted beneficiary (when set by PISP)  */
  isTrusted: Option[Boolean],
  creditorAgent: Option[FinancialInstitutionIdentification],
  creditor: PartyIdentification,
  creditorAccount: Option[AccountIdentification]
) extends ApiModel


