/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ClearingSystemMemberIdentification (
  /* ISO20022: Specification of a pre-agreed offering between clearing agents or the channel through which the payment instruction is processed.  */
  clearingSystemId: Option[String],
  /* ISO20022: Identification of a member of a clearing system.  */
  memberId: Option[String]
) extends ApiModel


