/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ErrorModel (
  /* current timestamp */
  timestamp: Option[DateTime],
  /* HTTP error code */
  status: Int,
  /* HTTP error text */
  error: Option[String],
  /* HTTP textual reason phrase */
  message: String,
  /* Relevant path that was used */
  path: Option[String]
) extends ApiModel


