/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GenericLink (
  /* URI to be used */
  href: String,
  /* specifies \"true\" if href is a URI template, i.e. with parameters. Otherwise, this property is absent or set to false */
  templated: Option[Boolean]
) extends ApiModel


