/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartyIdentification (
  /* ISO20022: Name by which a party is known and which is usually used to identify that party.  */
  name: String,
  postalAddress: Option[PostalAddress],
  /* Unique and unambiguous way to identify an organisation. */
  organisationId: Option[GenericIdentification],
  /* Unique and unambiguous identification of a person. */
  privateId: Option[GenericIdentification]
) extends ApiModel


