/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PaymentRequestResource (
  resourceId: Option[ResourceId],
  paymentInformationId: PaymentInformationId,
  creationDateTime: CreationDateTime,
  /* ISO20022: Number of individual transactions contained in the message. API: Each ASPSP will specify a maximum value for this field taking into accounts its specificities about payment request handling  */
  numberOfTransactions: Int,
  initiatingParty: PartyIdentification,
  paymentTypeInformation: PaymentTypeInformation,
  debtor: Option[PartyIdentification],
  debtorAccount: Option[AccountIdentification],
  debtorAgent: Option[FinancialInstitutionIdentification],
  beneficiary: Option[Beneficiary],
  ultimateCreditor: Option[PartyIdentification],
  purpose: Option[PurposeCode],
  chargeBearer: Option[ChargeBearerCode],
  paymentInformationStatus: Option[PaymentInformationStatusCode],
  statusReasonInformation: Option[StatusReasonInformation],
  fundsAvailability: Option[FundsAvailabilityInformation],
  booking: Option[BookingInformation],
  /* ISO20022: Date at which the initiating party requests the clearing agent to process the payment.   */
  requestedExecutionDate: Option[DateTime],
  /* ISO20022: Payment processes required to transfer cash from the debtor to the creditor. API: Each ASPSP will specify a maxItems value for this field taking into accounts its specificities about payment request handling  */
  creditTransferTransaction: Seq[CreditTransferTransaction],
  supplementaryData: SupplementaryData
) extends ApiModel


