/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PsuContextLinks (
  self: GenericLink,
  beneficiaries: Option[GenericLink],
  first: Option[GenericLink],
  last: Option[GenericLink],
  next: Option[GenericLink],
  prev: Option[GenericLink]
) extends ApiModel


